### DISCUSSION TITLE
Autoconfiguration via YAML

### DISCUSSION THREAD

**Discussion by eznix86** [vitodeploy/vito#482] [Ideas]
I believe it would be super nice if we have `vito init` cli tool using laravel zero.

then we have something like:

```yaml
name: vito
php: 8.4
domain:
      - vito.io
      - vito.us
    build:
      - 'COMPOSER_MIRROR_PATH_REPOS=1 composer install --verbose --prefer-dist --no-progress --no-interaction --optimize-autoloader --no-suggest --no-dev'
      - 'php artisan optimize'
      - 'php artisan event:cache'
      - 'php artisan view:cache'
      - 'npm ci && npm run build && rm -rf node_modules'
    deploy:
      - 'php artisan migrate --force'
services:
    redis:
        version: 7.0.0
    minio:
        version: RELEASE.2024-06-29
    mysql:
        version: 8.0.36
```

It makes a project configuration portable. We can have multiple environments, the possibilities are endless but the idea is to have a configuration file which autoconfigure everything. What would be left is environment variables
