### ISSUE TITLE
Docker: Something wrong with the cache

### ISSUE THREAD

**Issue by buddhaCode** [vitodeploy/vito#446]
**Describe the bug**
Installation via Docker doesn't work. Calling the page returns an empty response. Can see the following on the Docker logs:

```
2025-01-28 15:52:03 In Compiler.php line 67:
2025-01-28 15:52:03                                       
2025-01-28 15:52:03   Please provide a valid cache path.
```

**To Reproduce**
1. Followed the instructions from https://vitodeploy.com/getting-started/installation.html#docker-compose

**Expected behavior**
Can open Vito start page

**Screenshots**
-

**Additional context**
-

**Comment by saeedvaziry** [comment]
Are you providing any additional env variables than the ones have been mentioned in the docs?

**Comment by buddhaCode** [comment]
Nope.

**Comment by buddhaCode** [comment]
Here is my docker compose file:

```
version: "3"
services:
  vito:
    image: vitodeploy/vito:latest
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true
    ports:
      - 8002:80
    environment:
      APP_KEY: "base64:PvwKnXjpZTe39ni8X+dME1QBX7P8FHE+HXKhK6tyz8I="
      NAME: "vito"
      EMAIL: "dummy@foo.bar"
      PASSWORD: "1234"
    volumes:
      - ./vito:/var/www/html/storage
networks: {}

```

**Comment by saeedvaziry** [comment]
Could you please try `vitodeploy/vito:2.x` instead of the latest one?

**Comment by saeedvaziry** [comment]
and do you have this end of your docker-compose?
```
volumes:
  vito-storage:
    driver: local
```

**Comment by saeedvaziry** [comment]
my point: try to run it exactly according to the docs:

```
version: "3"
services:
  vito:
    image: vitodeploy/vito:latest
    ports:
      - "8000:80"
    environment:
      APP_KEY: "your-32-character-app-key"
      NAME: "vito"
      EMAIL: "vito@example.com"
      PASSWORD: "password"
    volumes:
      - "vito-storage:/var/www/html/storage"
volumes:
  vito-storage:
    driver: local
```
