### ISSUE TITLE
Unable to run in docker

### ISSUE THREAD

**Issue by M6268** [vitodeploy/vito#45]
When trying to run it in docker container, the following errors occured.
Am i doing it wrong or any specific instructions to run it in docker?

`docker-compose up -d`

 ```
=> ERROR [ 6/11] RUN groupadd --force -g  sail                                                                                                                                                                                                                                                                       0.2s
------
 > [ 6/11] RUN groupadd --force -g  sail:
0.203 groupadd: invalid group ID 'sail'
------
Dockerfile:51
--------------------
  49 |     RUN setcap "cap_net_bind_service=+ep" /usr/bin/php8.1
  50 |     
  51 | >>> RUN groupadd --force -g $WWWGROUP sail
  52 |     RUN useradd -ms /bin/bash --no-user-group -g $WWWGROUP -u 1337 sail
  53 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c groupadd --force -g $WWWGROUP sail" did not complete successfully: exit code: 3
ERROR: Service 'worker' failed to build : Build failed
```

**Comment by saeedvaziry** [comment]
Have you created the `.env` file and set the correct values?

Also I would recommend running docker with `sail` not just docker-comopse at the first execution.

**Comment by M6268** [comment]
Yes, i created the .env.
**But i didn't want to use sail.**
If you can provide any suggestion it would be much helpful to alot of people.

**Comment by gulasz101** [comment]
If you do not want to use sail just use official docker image, sail is not doing anything special except of giving you few  convenient commands.

As small exercise I made it running with alpine based image.

Below you have changes:
- dockerfile
```dockerfile
# Alpine.Dockerfile
ARG PHP_VERSION=8.1

FROM composer:latest AS composer
FROM php:${PHP_VERSION}-alpine

ENV TZ=UTC

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

COPY --from=composer /usr/bin/composer /usr/bin/composer

RUN apk add --update --no-cache \
    bash \
    git \
    zlib \
    gnupg \
    # gosu \
    curl \
    ca-certificates \
    zip \
    unzip \
    supervisor \
    sqlite \
    libcap \
    libpng-dev \
    python3 \
    bind-tools \
    librsvg \
    # fswatch \
    nodejs \
    npm


RUN npm install -g npm

RUN apk add --no-cache \
    yarn \
    mysql-client \
    postgresql15-client


COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin/

RUN install-php-extensions \
    # pgslq \
    sqlite3 \
    gd \
    imagick \
    curl \
    imap \
    # mysql \
    mbstring \
    ssh2 \
    xml \
    zip \
    bcmath \
    soap \
    intl \
    readline \
    ldap \
    msgpack \
    igbinary \
    redis \
    swoole \
    memcached \
    pcov \
    xdebug \
    sockets \
    zlib \
    ffi \
    redis \
    pdo \
    pdo_mysql \
    pdo_sqlite \
    pdo_pgsql

RUN addgroup -g "1000" -S sail \
  && adduser --system --gecos "" --ingroup "sail" --uid "1000" sail

USER sail

COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf

EXPOSE 8080
WORKDIR /var/www/html

CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]

```
- slightly adjusted docker compose file (changed built context, removed few env variables / args)
```yaml
version: '3'
services:
    vito:
        build:
            context: ./docker/8.1
            dockerfile: Alpine.Dockerfile
        image: vito/app
        ports:
            - '80:80'
        volumes:
            - '.:/var/www/html'
            - ./storage/logs/:/var/log/supervisor/
        depends_on:
            - mysql
            - redis
    worker:
        build:
            context: ./docker/8.1
            dockerfile: Alpine.Dockerfile
        image: vito/app
        command: php artisan queue:listen --timeout=600 --queue=default,ssh,ssh-long
        volumes:
            - '.:/var/www/html'
            - ./storage/logs/:/var/log/supervisor/
        restart: unless-stopped
        depends_on:
            - mysql
            - redis
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'sail-mysql:/var/lib/mysql'
            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
            retries: 3
            timeout: 5s
    redis:
        image: redis:latest
volumes:
    sail-mysql:
        driver: local
```
- `.env` I used:
```
APP_NAME=Vito
APP_ENV=local
APP_KEY=base64:A8DmAuAl0eP8A0Y+sUoz+0pGwWl3kOwbEazbcF6qUWg=
APP_DEBUG=true
APP_URL=http://vito.test

LOG_CHANNEL=stack
LOG_LEVEL=debug

DB_CONNECTION=mysql
DB_HOST=mysql
DB_PORT=3306
DB_DATABASE=vito
DB_USERNAME=root
DB_PASSWORD=

BROADCAST_DRIVER=null
CACHE_DRIVER=file
FILESYSTEM_DRIVER=local
QUEUE_CONNECTION=default
SESSION_DRIVER=database
SESSION_LIFETIME=120

REDIS_HOST=redis
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_MAILER=smtp
MAIL_HOST=mailhog
MAIL_PORT=1025
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null
MAIL_FROM_ADDRESS=null
MAIL_FROM_NAME="${APP_NAME}"

SSH_PUBLIC_KEY_NAME=ssh-public.key
SSH_PRIVATE_KEY_NAME=ssh-private.pem
```

keep in mind that artisan is not a command added to a $PATH in this case, so to run anything I would suggest doing something like:
```shell
docker compose exec vito php artisan migrate
```
- and final adjustment, since paths are little bit different for alpine, and for my convenience I changed user in image, there is small change to `supervisor` config
```conf
[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:php]
command=php -d variables_order=EGPCS /var/www/html/artisan serve --host=0.0.0.0 --port=80
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

```

Most likely dockerfile does not need all added above, but wanted to stick as close as possible to what was `vito` shipped with.
