### ISSUE TITLE
Aws provider error

### ISSUE THREAD

**Issue by vine1993** [vitodeploy/vito#572]
**Describe the bug**
Erro 500 when selecting a provider on server creation

**To Reproduce**
1. Create an AWS Provider
2. Create a new Server and choose AWS
3. on the field "Server provider connection" choose you was provider

**Expected behavior**
Not having the error at all, or show a custom error with the was issue

**Screenshots**

![Image](https://github.com/user-attachments/assets/d71129d2-e4aa-4caa-9fa6-8e21759d5e8f)

![Image](https://github.com/user-attachments/assets/1845d9d6-ef1d-4dd6-9f67-3211d01f56c5)

**Additional context**
Localhost with docker compose

```
services:
  vito:
    image: vitodeploy/vito:latest
    ports:
      - "9000:80"
    environment:
      APP_KEY: "base64:FM9ybbvJh3EeRJ72m94+JJLR5v4BH2WE5cDLsfD5kes="
      NAME: "Vinicius Rangel"
      EMAIL: "****"
      PASSWORD: "***"
      APP_DEBUG: true
    volumes:
      - "vito-storage:/var/www/html/storage"
volumes:
  vito-storage:
    driver: local
```
